<a href="https://colab.research.google.com/github/AhmedMahmoudMetwally/Employee-Churn-Analysis-/blob/main/Data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
url = "/content/drive/MyDrive/Colab Notebooks/NTI/Projects/Employee TurnOver/df_encoded.csv"

In [4]:
df_encoded = pd.read_csv(url)

In [5]:
df_encoded.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,quit,promotion_last_5years,salary,department_IT,department_RandD,department_accounting,department_hr,department_management,department_marketing,department_product_mng,department_sales,department_support,department_technical,hours_level
0,0.38,0.53,2,157,3,0,1,0,0,False,False,False,False,False,False,False,True,False,False,0
1,0.80,0.86,5,262,6,0,1,0,1,False,False,False,False,False,False,False,True,False,False,3
2,0.11,0.88,7,272,4,0,1,0,1,False,False,False,False,False,False,False,True,False,False,3
3,0.72,0.87,5,223,5,0,1,0,0,False,False,False,False,False,False,False,True,False,False,2
4,0.37,0.52,2,159,3,0,1,0,0,False,False,False,False,False,False,False,True,False,False,0

In [6]:
df_encoded.isnull().sum()

satisfaction_level        0
last_evaluation           0
number_project            0
average_montly_hours      0
time_spend_company        0
Work_accident             0
quit                      0
promotion_last_5years     0
salary                    0
department_IT             0
department_RandD          0
department_accounting     0
department_hr             0
department_management     0
department_marketing      0
department_product_mng    0
department_sales          0
department_support        0
department_technical      0
hours_level               0
dtype: int64

#**Tasks :**
#- Handle outliers
#- Handling Missing values
#- Handle Class Imbalance
#- Scalling
#- Encode categorical variables
#- Drop Irrelevant Columns

# Split The Data

In [7]:
X = df_encoded.drop(columns = "quit")
y = df_encoded["quit"]

In [8]:
X.shape, y.shape

((14999, 19), (14999,))

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y , test_size=0.2,random_state=42,stratify=y)

In [10]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((11999, 19), (3000, 19), (11999,), (3000,))

Apply preprocessing steps only on training data

Outlier handling

Scaling (fit on train, transform on both train and test)

SMOTE or other balancing (only on train)

Feature engineering

# Handle Outliers